version: "3"
services:
  iyang-nginx:
    image: yangzhyo/iyang-nginx
    ports:
      - "80:80"
    volumes:
      - "/opt:/app"
  iyang-webhook:
    image: yangzhyo/iyang-webhook
    ports:
      - "9000:9000"
    volumes:
      - "/opt:/app"
